GET http://localhost:8000/products/ HTTP/1.1

###
GET http://localhost:8000/products/2/ HTTP/1.1

###
PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTkzNTkzLCJpYXQiOjE3NDU1OTMyOTMsImp0aSI6IjIyZTAzNjNmNDk5ZTQxYmY4NTI3Mjc5MmEwZmY4YTA2IiwidXNlcl9pZCI6MX0.jUIDIiNPriGGdZzs8aKSIxJYi84AVNjWRHSyvW_BMIQ

{
    "name": "put1",
    "price": 300.00,
    "stock": 14,
    "description": "New TV1"
}

###
DELETE http://localhost:8000/products/2/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTkzNTkzLCJpYXQiOjE3NDU1OTMyOTMsImp0aSI6IjIyZTAzNjNmNDk5ZTQxYmY4NTI3Mjc5MmEwZmY4YTA2IiwidXNlcl9pZCI6MX0.jUIDIiNPriGGdZzs8aKSIxJYi84AVNjWRHSyvW_BMIQ



###
POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTA2OTYzLCJpYXQiOjE3NDU1MDY2NjMsImp0aSI6IjRkMzY3YjU3MWUzNjQzM2NiZDAwZWI3OGFhNWE5MzU2IiwidXNlcl9pZCI6MX0.ZeGBSWkNAvwXlcP0Nc0tUmK0UXMFk-Ds1cEwBmRd_1I

{
    "name": "TVdatnt",
    "price": 300.00,
    "stock": 14,
    "description": "New TV1"
}

###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "datnt1171",
    "password": "lkjhgnhI1@"
}

###
GET http://localhost:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ1NTA2OTYzLCJpYXQiOjE3NDU1MDY2NjMsImp0aSI6IjRkMzY3YjU3MWUzNjQzM2NiZDAwZWI3OGFhNWE5MzU2IiwidXNlcl9pZCI6MX0.ZeGBSWkNAvwXlcP0Nc0tUmK0UXMFk-Ds1cEwBmRd_1I

###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0NTY3NzU5MiwiaWF0IjoxNzQ1NTkxMTkyLCJqdGkiOiJiMjJmOTQ4N2Q1MWU0OGJjYTExZWQ4YWJhY2NhOTQwYiIsInVzZXJfaWQiOjF9.2QexBxxC2xJxeofKPA7YEIS7DNyYuiiL4aqu2Q0iygQ"
}

###

GET http://localhost:8000/orders/a27af9f9-5320-4cf4-99b6-e8737ab24176 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MDE5ODY5LCJpYXQiOjE3NDYwMTk1NjksImp0aSI6Ijg1OTI0OTg0MGRjZDQ2ZmNiMmRkMTJjOWZiYTY1NzljIiwidXNlcl9pZCI6Mn0.HkCK9AG8etJgAOpZs_oVgVbJIv32VUxYvlY39G_trQo


###
POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2MDc3NzM5LCJpYXQiOjE3NDYwNzc0MzksImp0aSI6ImI4ZGJlNTcyZjk0YzRmOGVhZDM5NzVmOWNmZTAwNmJiIiwidXNlcl9pZCI6Mn0.uPuj9rsiYIrIc_9u9EmEgIQFKvm27vdzOtOB4niYx8c

{
    "status": "Pending",
    "user": 1,
    "items": [
        {
            "product": 4,
            "quantity": 2
        },
        {
            "product": 3,
            "quantity": 1
        }
    ]
}